--ESTADOS
INSERT INTO TBL_ESTADOS(ID, NOMBRE) VALUES(1, 'Completada');
INSERT INTO TBL_ESTADOS(ID, NOMBRE) VALUES(2, 'No completada');
--PRIORIDADES
INSERT INTO TBL_PRIORIDADES(ID, NOMBRE) VALUES(1, 'Alta');
INSERT INTO TBL_PRIORIDADES(ID, NOMBRE) VALUES(2, 'Media');
INSERT INTO TBL_PRIORIDADES(ID, NOMBRE) VALUES(3, 'Baja');

--TBL_TAREAS
--INSERT INTO TBL_TAREAS(ID_TAREA, NOMBRE, PRIORIDAD, ESTADO) VALUES(1, 'Revisar la ejecucion de la aplicacion', 1, 1 );
--INSERT INTO TBL_TAREAS(ID_TAREA, NOMBRE, PRIORIDAD, ESTADO) VALUES(2, 'Cerrar la aplicacion', 1, 2 );
--INSERT INTO TBL_TAREAS(ID_TAREA, NOMBRE, PRIORIDAD, ESTADO) VALUES(3, 'Revisar los hilos de pagos', 1, 1 );
--INSERT INTO TBL_TAREAS(ID_TAREA, NOMBRE, PRIORIDAD, ESTADO) VALUES(4, 'Configurar el despliegue en produccion', 2, 2 );
--INSERT INTO TBL_TAREAS(ID_TAREA, NOMBRE, PRIORIDAD, ESTADO) VALUES(5, 'Revisar configuracion de la base de datos productiva', 3, 2 );
--INSERT INTO TBL_TAREAS(ID_TAREA, NOMBRE, PRIORIDAD, ESTADO) VALUES(6, 'Monitoreo de aplicaciones', 2, 1 );


